version: '3.3'

version: '3.3'

services:
  blog_db:
    container_name: blog_db
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'ca_blog_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '5455:5455'
    volumes:
      - 'blog_db_data:/var/lib/mysql'

  blog_app:
    container_name: blog_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: blog_app_img
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5455/blog_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: default,in_docker
    ports:
      - '8080:8080'

volumes:
  blog_db_data: